name: Scoping Out the Data
favicon: null
layout_spectrum: 0.36963
typography_spectrum: 0.75376
title: Scoping Out the Data
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#28201e'
    - '#d4532b'
    - '#4b7776'
    - '#a09999'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
