name: Scoping Out the Data
favicon: null
layout_spectrum: 0.16253169113770127
typography_spectrum: 0.3161429895553738
title: Scoping Out the Data
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070512'
    - '#ffffff'
    - '#675e67'
    - '#ab9b57'
    - '#cbc093'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
