name: Scoping Out the Data
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72245
title: Scoping Out the Data
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000015'
    - '#082940'
    - '#17506c'
    - '#2c8297'
    - '#c5d4cb'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
